import test from 'node:test';import assert from 'node:assert/strict';import {createCipheriv,createHash} from 'node:crypto';
import {decryptWecom,parseXml,parseFeedbackCommand,readWecomConfig,verifyWecomSignature} from '../apps/zhixing-api/wecom.ts';
const key=Buffer.from(Array.from({length:32},(_,i)=>i));const cfg={corpId:'ww-test',agentId:'1000001',token:'test-token',aesKey:key.toString('base64').slice(0,-1),secret:'secret',enabled:false};
// Independent protocol producer, never calls implementation encryption.
export function vector(xml:string,corp='ww-test'){const bytes=Buffer.from(xml);const len=Buffer.alloc(4);len.writeUInt32BE(bytes.length);const raw=Buffer.concat([Buffer.alloc(16,7),len,bytes,Buffer.from(corp)]);const n=32-raw.length%32;const cipher=createCipheriv('aes-256-cbc',key,key.subarray(0,16));cipher.setAutoPadding(false);return Buffer.concat([cipher.update(Buffer.concat([raw,Buffer.alloc(n,n)])),cipher.final()]).toString('base64');}
test('independent AES CBC frame and signatures reject forgery, wrong corp and stale time',()=>{const enc=vector('<xml><Content><![CDATA[你好]]></Content></xml>');assert.equal(decryptWecom(cfg,enc),'<xml><Content><![CDATA[你好]]></Content></xml>');assert.throws(()=>decryptWecom(cfg,vector('x','other')),/FORBIDDEN/);const ts='1800000000';const sign=createHash('sha1').update([cfg.token,ts,'nonce',enc].sort().join('')).digest('hex');verifyWecomSignature(cfg,ts,'nonce',enc,sign,1800000000000);assert.throws(()=>verifyWecomSignature(cfg,ts,'nonce',enc,'0'.repeat(40),1800000000000),/FORBIDDEN/);assert.throws(()=>verifyWecomSignature(cfg,ts,'nonce',enc,sign,1800000400000),/FORBIDDEN/);});
test('bounded XML rejects DTD, duplicates, nesting and malformed entities',()=>{assert.deepEqual(parseXml('<xml><A><![CDATA[a&b]]></A><B>1&amp;2</B></xml>'),{A:'a&b',B:'1&2'});for(const xml of ['<!DOCTYPE xml><xml/>','<xml><A>1</A><A>2</A></xml>','<xml><A><B>1</B></A></xml>','<xml><A>&evil;</A></xml>','x'.repeat(100000)])assert.throws(()=>parseXml(xml),/VALIDATION_ERROR/);});
test('controlled feedback requires explicit association/version and never guesses prose',()=>{assert.deepEqual(parseFeedbackCommand('反馈 SH-1 assembly v3 数量2/10 预计2026-09-20'),{orderId:'SH-1',nodeId:'assembly',expectedVersion:3,mode:'quantity',completed:2,total:10,expectedFinish:'2026-09-20'});assert.equal(parseFeedbackCommand('反馈 SH-1 assembly v3 百分比40%').percent,40);for(const s of ['今天好了四成','反馈 SH-1 assembly 数量2/10','反馈 SH-1 assembly v3 数量11/10','反馈 SH-1 assembly v3 百分比101%','反馈 SH-1 assembly v3 数量2/10 预计2026-02-30'])assert.throws(()=>parseFeedbackCommand(s),/VALIDATION_ERROR/);assert.equal(readWecomConfig({}),null);});
import Fastify from 'fastify';import {installWecom} from '../apps/zhixing-api/wecom.ts';
test('GET callback decrypts exact echo; forged POST is rejected before database access',async()=>{const app=Fastify();let touched=false;const db={connect:async()=>{touched=true;throw new Error('should not reach');}};installWecom(app,db as any,async()=>({}),cfg);const timestamp=String(Math.floor(Date.now()/1000)),nonce='abc',echostr=vector('echo-verified');const sig=createHash('sha1').update([cfg.token,timestamp,nonce,echostr].sort().join('')).digest('hex');try{const r=await app.inject({method:'GET',url:'/api/wecom/callback?'+new URLSearchParams({timestamp,nonce,echostr,msg_signature:sig})});assert.equal(r.statusCode,200);assert.equal(r.body,'echo-verified');const bad=await app.inject({method:'POST',url:'/api/wecom/callback?'+new URLSearchParams({timestamp,nonce,msg_signature:'0'.repeat(40)}),headers:{'content-type':'application/xml'},payload:`<xml><Encrypt>${echostr}</Encrypt></xml>`});assert.equal(bad.statusCode,403);assert.equal(touched,false);}finally{await app.close();}});
