import {useMembers} from './Members';
import {previewProjectBatch,validateProject} from '../../../packages/sampling-contracts/project-validation.ts';
import type {ProjectTemplate} from '../../../apps/sample-reference-service/project.ts';
import {useEffect,useRef,useState} from 'react';
import {Alert,Button,Form,Input,InputNumber,Modal,Select} from 'antd';

const templates=[['requirements','需求确认'],['structure','结构设计'],['electronics','电子调试'],['assembly','样机装配'],['acoustics','声学测试'],['quality','品质检验'],['shipping','寄样']];
export function ProjectEditor({pending,onCancel,onSave,api,onBatch,existingOrderIds}:{existingOrderIds:string[];pending:boolean;onCancel:()=>void;onSave:(input:unknown)=>void;api:(path:string,body?:unknown,key?:string)=>Promise<any>;onBatch:(input:unknown)=>void}){
 const {people,ownerOptions,isManager}=useMembers();
  const [form]=Form.useForm();const[mode,setMode]=useState('form');const[raw,setRaw]=useState('');const[error,setError]=useState('');
  const[library,setLibrary]=useState<ProjectTemplate[]>([]);const[templateId,setTemplateId]=useState<string>();const[templateName,setTemplateName]=useState('');const[templatePending,setTemplatePending]=useState(false);const[preview,setPreview]=useState<{valid:boolean;errors:{row:number;code:string}[]}|null>(null);
  const existingIdsKey=JSON.stringify(existingOrderIds);
  useEffect(()=>setPreview(null),[existingIdsKey]);
  const templateKey=useRef<{payload:string;key:string;id:string}|null>(null);
  useEffect(()=>{void api('/api/soundlab/templates').then(setLibrary).catch((e:Error)=>setError(e.message));},[]);
  function formProject(values:any){return {id:values.id,product:values.product,customer:values.customer,due:values.due,calendar:{weekdays:values.weekdays,holidays:values.holidays.split(',').map((s:string)=>s.trim()).filter(Boolean)},nodes:values.nodes};}
  async function templateWrite(remove=false){setTemplatePending(true);try{const current=library.find(t=>t.id===templateId);const project=remove?undefined:mode==='form'?formProject(await form.validateFields()):JSON.parse(raw);if(!remove)validateProject(project);const id=current?.id??templateKey.current?.id??crypto.randomUUID();const body=remove?{expectedVersion:current?.version}:{id,name:templateName,project,...(current?{expectedVersion:current.version}:{})};const path=remove?'/api/soundlab/templates/'+encodeURIComponent(current!.id)+'/delete':'/api/soundlab/templates';const payload=JSON.stringify({path,body});if(templateKey.current?.payload!==payload)templateKey.current={payload,key:crypto.randomUUID(),id};const saved=await api(path,body,templateKey.current.key) as ProjectTemplate;setLibrary(previous=>remove?previous.filter(t=>t.id!==id):[...previous.filter(t=>t.id!==saved.id),saved].sort((a,b)=>a.id.localeCompare(b.id)));setTemplateId(remove?undefined:saved.id);templateKey.current=null;setError('');}catch(e){setError(e instanceof Error?e.message:'模板保存失败');}finally{setTemplatePending(false);}}
  return <Modal title="新建打样项目" open width={880} onCancel={onCancel} footer={null}>
    <Select value={mode} onChange={setMode} options={[{value:'form',label:'按音响打样模板创建'},{value:'json',label:'导入单个项目 JSON'},{value:'batch',label:'批量导入 JSON（最多 50 个）'}]}/>
    <div className="quantity-grid"><Select placeholder="选择租户模板" allowClear value={templateId} options={library.map(t=>({value:t.id,label:t.name+' · v'+t.version}))} onChange={id=>{setTemplateId(id);const t=library.find(t=>t.id===id);if(t){setTemplateName(t.name);setMode('form');form.setFieldsValue({...t.project,weekdays:t.project.calendar.weekdays,holidays:t.project.calendar.holidays.join(',')});}}}/><Input aria-label="模板名称" placeholder="模板名称" value={templateName} onChange={e=>setTemplateName(e.target.value)}/><Button loading={templatePending} disabled={mode==='batch'} onClick={()=>void templateWrite()}>{templateId?'更新当前模板':'保存为新模板'}</Button>{templateId&&<Button danger loading={templatePending} onClick={()=>void templateWrite(true)}>删除模板</Button>}</div>
    {error&&<Alert type="error" title={error}/>}
    {mode==='batch'?<><p>粘贴项目数组。预览通过后整批提交；任意项目不合法或单号已存在，整批均不写入。如提交时发生编号冲突，请等待订单刷新后重新预览。</p><Input.TextArea aria-label="批量项目 JSON" rows={12} value={raw} onChange={e=>{setRaw(e.target.value);setPreview(null);}}/><Button onClick={()=>{try{setPreview(previewProjectBatch(JSON.parse(raw),existingOrderIds));setError('');}catch{setPreview(null);setError('JSON 格式不正确');}}}>预览并校验</Button>{preview&&<Alert type={preview.valid?'success':'error'} title={preview.valid?'项目配置校验通过；提交时将检查已有单号。':preview.errors.map(e=>(e.row?'第 '+e.row+' 项：':'')+e.code).join('；')}/>}<Button type="primary" loading={pending} disabled={!preview?.valid} onClick={()=>onBatch({projects:JSON.parse(raw)})}>确认整批导入</Button></>:mode==='json'?<><p>导入项目字段：id、product、customer、due、calendar，以及 nodes。节点必须包含 id、name、owner、due、weight、durationDays、dependencies 和 acceptanceCriteria。</p><Input.TextArea aria-label="项目 JSON" rows={12} value={raw} onChange={e=>setRaw(e.target.value)}/>{error&&<Alert type="error" title={error}/>}<Button type="primary" loading={pending} onClick={()=>{try{onSave(JSON.parse(raw));setError('');}catch{setError('JSON 格式不正确');}}}>校验并导入</Button></>:<Form form={form} layout="vertical" initialValues={{weekdays:[1,2,3,4,5],holidays:'',nodes:templates.map(([id,name],i)=>({id,name,owner:ownerOptions[0]?.value,durationDays:1,weight:1/7,dependencies:i?[templates[i-1][0]]:[],acceptanceCriteria:'负责人检查并确认通过'}))}} onFinish={values=>onSave(formProject(values))}>
      <div className="quantity-grid"><Form.Item name="id" label="打样单号" rules={[{required:true,pattern:/^[\w-]+$/}]}><Input maxLength={60} placeholder="例如 S26-001"/></Form.Item><Form.Item name="product" label="产品" rules={[{required:true}]}><Input maxLength={120}/></Form.Item><Form.Item name="customer" label="客户" rules={[{required:true}]}><Input maxLength={120}/></Form.Item><Form.Item name="due" label="目标寄样日期" rules={[{required:true}]}><Input type="date"/></Form.Item></div>
      <Form.Item name="weekdays" label="工作日" rules={[{required:true}]}><Select mode="multiple" options={['日','一','二','三','四','五','六'].map((s,value)=>({value,label:'周'+s}))}/></Form.Item><Form.Item name="holidays" label="休息日期（逗号分隔，例如 2026-10-01,2026-10-02）"><Input/></Form.Item>
      <Alert type="info" title="模板默认串行流程。工期按工作日计算；权重合计必须为 1。可在 JSON 导入中配置其他节点及并行依赖。"/>
      <Form.List name="nodes">{fields=>fields.map(field=><div className="project-node-editor" key={field.key}><h4>{form.getFieldValue(['nodes',field.name,'name'])??'节点'}</h4><Form.Item name={[field.name,'id']} hidden><Input/></Form.Item><Form.Item name={[field.name,'name']} hidden><Input/></Form.Item><Form.Item name={[field.name,'dependencies']} hidden><Select mode="multiple"/></Form.Item><div className="quantity-grid"><Form.Item name={[field.name,'owner']} label="负责人" rules={[{required:true}]}><Select options={ownerOptions}/></Form.Item><Form.Item name={[field.name,'due']} label="计划完成" rules={[{required:true}]}><Input type="date"/></Form.Item><Form.Item name={[field.name,'durationDays']} label="工期（工作日）" rules={[{required:true}]}><InputNumber min={1} max={365} precision={0}/></Form.Item><Form.Item name={[field.name,'weight']} label="进度权重" rules={[{required:true}]}><InputNumber min={0.000001} max={1} step={0.01}/></Form.Item></div><Form.Item name={[field.name,'acceptanceCriteria']} label="验收标准" rules={[{required:true}]}><Input maxLength={500}/></Form.Item></div>)}</Form.List>
      <Button type="primary" htmlType="submit" loading={pending} block>创建项目并纳入跟踪</Button>
    </Form>}
  </Modal>;
}


