import {useMembers} from './Members';
import {Alert,Button,Form,Input,InputNumber,Modal,Select} from 'antd';import {type Order} from '../../../packages/sampling-contracts/index.ts';
export function WorkflowEditor({order,pending,onCancel,onSave}:{order:Order;pending:boolean;onCancel:()=>void;onSave:(input:unknown)=>void}){
 const {people,ownerOptions,isManager}=useMembers();
 const nodes=order.nodes.map(n=>({id:n.id,name:n.name,owner:n.owner,due:n.due,weight:n.weight,dependencies:n.dependencies??[],durationDays:n.durationDays,plannedStart:n.plannedStart,acceptanceCriteria:n.acceptanceCriteria}));
 return <Modal title={`${order.id} · 配置节点流程`} open width={900} onCancel={onCancel} footer={null}><Alert type="info" title={`依据版本 v${order.version}；保留已有进度、反馈和验收记录。目标寄样日期通过变更审批调整。`} description="历史节点缺失的工期、依赖和验收标准请按实际情况补齐。未选择前置节点表示可以独立开始。"/>
  <Form layout="vertical" initialValues={{nodes,weekdays:order.calendar?.weekdays??[1,2,3,4,5],holidays:order.calendar?.holidays.join(',')??''}} onFinish={v=>onSave({expectedVersion:order.version,calendar:{weekdays:v.weekdays,holidays:v.holidays.split(',').map((s:string)=>s.trim()).filter(Boolean)},nodes:v.nodes.map((n:any)=>({...n,plannedStart:n.plannedStart||undefined}))})}>
   <Form.Item name="weekdays" label="工作日" rules={[{required:true}]}><Select mode="multiple" options={['日','一','二','三','四','五','六'].map((s,value)=>({value,label:'周'+s}))}/></Form.Item><Form.Item name="holidays" label="休息日期（以逗号分隔）"><Input/></Form.Item>
   <Form.List name="nodes">{fields=>fields.map(field=><div className="project-node-editor" key={field.key}><Form.Item name={[field.name,'id']} hidden><Input/></Form.Item><div className="quantity-grid"><Form.Item name={[field.name,'name']} label="节点名称" rules={[{required:true}]}><Input maxLength={100}/></Form.Item><Form.Item name={[field.name,'owner']} label="负责人" rules={[{required:true}]}><Select options={ownerOptions}/></Form.Item><Form.Item name={[field.name,'due']} label="计划完成" rules={[{required:true}]}><Input type="date"/></Form.Item><Form.Item name={[field.name,'plannedStart']} label="最早计划开始"><Input type="date"/></Form.Item><Form.Item name={[field.name,'durationDays']} label="工期（工作日）" rules={[{required:true}]}><InputNumber min={1} max={365} precision={0}/></Form.Item><Form.Item name={[field.name,'weight']} label="进度权重" rules={[{required:true}]}><InputNumber min={0.000001} max={1}/></Form.Item></div><Form.Item name={[field.name,'dependencies']} label="前置节点"><Select mode="multiple" options={nodes.filter(n=>n.id!==nodes[field.name].id).map(n=>({value:n.id,label:n.name}))}/></Form.Item><Form.Item name={[field.name,'acceptanceCriteria']} label="验收标准" rules={[{required:true}]}><Input maxLength={500}/></Form.Item></div>)}</Form.List><Button block type="primary" htmlType="submit" loading={pending}>保存流程配置</Button>
  </Form></Modal>;
}
