import test from 'node:test';import assert from 'node:assert/strict';import {Pool} from 'pg';import {randomUUID} from 'node:crypto';import {readFile} from 'node:fs/promises';
import {enqueueChat,listChat,runChat} from '../../apps/platform-worker/chat.ts';
import {chatToolToken,queryChatOrders} from '../../apps/platform-api/chat-tools.ts';
test('chat isolates histories, deduplicates submissions and does not retry unknown model outcomes',async()=>{
 const connectionString='postgresql://soundlab_platform:platform-local-only@127.0.0.1:55439/soundlab_platform',schema='test_chat_'+randomUUID().replaceAll('-','');const admin=new Pool({connectionString});await admin.query(`CREATE SCHEMA ${schema}`);const db=new Pool({connectionString,options:`-c search_path=${schema}`});
 try{await db.query(await readFile(new URL('../../migrations/platform/005-members.sql',import.meta.url),'utf8'));await db.query(await readFile(new URL('../../migrations/platform/006-chat.sql',import.meta.url),'utf8'));await db.query("INSERT INTO tenant_members VALUES('one','alice','Alice','member',true,1),('two','alice','Alice','member',true,1)");await db.query(await readFile(new URL('../../migrations/platform/007-chat-evidence.sql',import.meta.url),'utf8'));const p={tenant:'one',actor:'alice'},id=randomUUID();
 await enqueueChat(db,p,{id,message:'你好'});await enqueueChat(db,p,{id,message:'你好'});await assert.rejects(enqueueChat(db,p,{id:randomUUID(),message:'再问'}),/CHAT_BUSY/);assert.deepEqual(await listChat(db,{tenant:'two',actor:'alice'}),[]);
 let calls=0;await runChat(db,async prompt=>{calls++;assert.match(prompt,/你好/);return {summary:'你好，我是声研助理。',model:'test-model'};});assert.equal((await listChat(db,p))[0].answer,'你好，我是声研助理。');await enqueueChat(db,p,{id:randomUUID(),message:'继续'});await runChat(db,async prompt=>{calls++;assert.match(prompt,/你好，我是声研助理/);throw Error('secret provider error');});assert.equal((await listChat(db,p)).at(-1).error_code,'MODEL_CHAT_FAILED');await runChat(db,async()=>{calls++;return{};});assert.equal(calls,2);
 await assert.rejects(enqueueChat(db,{tenant:'two',actor:'alice'},{id,message:'你好'}),/IDEMPOTENCY_CONFLICT/);
 const toolId=randomUUID();await enqueueChat(db,p,{id:toolId,message:'查看A26-020进度'});await db.query("UPDATE chat_messages SET status='running' WHERE id=$1",[toolId]);const token=chatToolToken('local-secret',toolId);
 const evidence=await queryChatOrders(db,'local-secret',token,async principal=>{assert.equal(principal.tenant,'one');return [{id:'A26-020',version:2,product:'音箱',risk:'normal',due:'2026-09-20',nodes:[]}];});assert.equal(evidence.orders[0].version,2);assert.equal((await listChat(db,p)).at(-1).evidence.length,1);assert.equal((await listChat(db,{tenant:'two',actor:'alice'})).length,0);
 await db.query("UPDATE chat_messages SET status='completed' WHERE id=$1",[toolId]);await assert.rejects(queryChatOrders(db,'local-secret',token,async()=>{throw Error('must not invoke');}),/FORBIDDEN/);
 }finally{await db.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
});
