import test from 'node:test';import assert from 'node:assert/strict';import {Pool} from 'pg';import {randomUUID} from 'node:crypto';import * as polling from '../../apps/platform-worker/event-poll.ts';
test('event polling discovers tenants and maintains isolated cursors without unauthorized analysis',async()=>{const connectionString='postgresql://soundlab_platform:platform-local-only@127.0.0.1:55439/soundlab_platform';const admin=new Pool({connectionString});const schema='test_poll_'+randomUUID().replaceAll('-','');await admin.query(`CREATE SCHEMA ${schema}`);const db=new Pool({connectionString,options:`-c search_path=${schema}`});try{await db.query(`CREATE TABLE auth_users(tenant text,enabled boolean);CREATE TABLE patrol_policy(tenant text);CREATE TABLE worker_cursor(name text PRIMARY KEY,value bigint);CREATE TABLE activity(event_id text PRIMARY KEY,tenant text,object_id text,version int,summary text);INSERT INTO auth_users VALUES('demo',true),('other',true);INSERT INTO patrol_policy VALUES('third');`);assert.deepEqual(await polling.workerTenants(db),['demo','other','third']);let after='';const transport=async(input:any,init:any)=>{const tenant=init.headers['x-tenant'];after=String(input);return new Response(JSON.stringify([{id:tenant+'-event',tenant,object_id:'NEW',version:1,sequence:tenant==='demo'?'100':'1'}]));};await polling.pollTenantEvents(db,'demo','fake-key',transport);await polling.pollTenantEvents(db,'other','fake-key',transport);assert.match(after,/after=0$/);assert.equal((await db.query("SELECT value FROM worker_cursor WHERE name='sample-events:other'")).rows[0].value,'1');await assert.rejects(polling.pollTenantEvents(db,'third','fake-key',async()=>new Response(JSON.stringify([{id:'evil',tenant:'demo',object_id:'NEW',version:1,sequence:'3'}]))),/TENANT_MISMATCH/);assert.equal((await db.query("SELECT count(*)::int n FROM activity WHERE tenant='third'")).rows[0].n,0);}finally{await db.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}});
test('explicit demo mode bootstraps empty tenant registry and adopts only its legacy cursor',async()=>{
 const connectionString='postgresql://soundlab_platform:platform-local-only@127.0.0.1:55439/soundlab_platform';const admin=new Pool({connectionString});const schema='test_poll_legacy_'+randomUUID().replaceAll('-','');await admin.query(`CREATE SCHEMA ${schema}`);const db=new Pool({connectionString,options:`-c search_path=${schema}`});
 try{await db.query(`CREATE TABLE auth_users(tenant text,enabled boolean);CREATE TABLE patrol_policy(tenant text);CREATE TABLE worker_cursor(name text PRIMARY KEY,value bigint);INSERT INTO worker_cursor VALUES('sample-events',42)`);
 assert.deepEqual(await polling.workerTenants(db,{SOUNDLAB_DEMO_MODE:'true'}),['demo']);assert.deepEqual(await polling.workerTenants(db,{SOUNDLAB_DEMO_MODE:'false'}),[]);assert.deepEqual(await polling.workerTenants(db,{}),[]);
 const urls:string[]=[];const transport:typeof fetch=async input=>{urls.push(String(input));return new Response('[]')};await polling.pollTenantEvents(db,'demo','test-key',transport);assert.match(urls.at(-1)!,/after=42$/);assert.equal((await db.query("SELECT value FROM worker_cursor WHERE name='sample-events:demo'")).rows[0].value,'42');
 await polling.pollTenantEvents(db,'other','test-key',transport);assert.match(urls.at(-1)!,/after=0$/);
 await db.query("UPDATE worker_cursor SET value=43 WHERE name='sample-events:demo';UPDATE worker_cursor SET value=99 WHERE name='sample-events'");await polling.pollTenantEvents(db,'demo','test-key',transport);assert.match(urls.at(-1)!,/after=43$/);
 }finally{await db.end();await admin.query(`DROP SCHEMA ${schema} CASCADE`);await admin.end();}
});
