import type {WecomConfig} from './wecom.ts';
export type SendResult={status:'disabled'|'sent'|'failed'|'unknown';code?:string;messageId?:string};
export function createWecomSender(config:WecomConfig,transport:typeof fetch=fetch,now:()=>number=Date.now){let token='',expires=0;let loading:Promise<string>|null=null;
 async function getToken(){if(token&&now()<expires)return token;if(loading)return loading;loading=(async()=>{const url=new URL('https://qyapi.weixin.qq.com/cgi-bin/gettoken');url.searchParams.set('corpid',config.corpId);url.searchParams.set('corpsecret',config.secret);const r=await transport(url,{redirect:'error',signal:AbortSignal.timeout(5000)});const data=await r.json() as any;if(!r.ok||data.errcode!==0||typeof data.access_token!=='string'||!data.access_token||!Number.isFinite(data.expires_in)||data.expires_in<=60)throw new Error('TOKEN_UNAVAILABLE');token=data.access_token;expires=now()+(data.expires_in-60)*1000;return token;})().finally(()=>{loading=null;});return loading;}
 return {async sendText(toUser:string,content:string):Promise<SendResult>{if(!config.enabled)return {status:'disabled'};if(!config.secret||toUser.toLowerCase()==='@all'||!/^[A-Za-z0-9_.@-]{1,100}$/.test(toUser)||!content||Buffer.byteLength(content)>2048)return {status:'failed',code:'INVALID_SEND_CONFIG_OR_INPUT'};let access:string;try{access=await getToken();}catch{return {status:'failed',code:'TOKEN_UNAVAILABLE'};}
 try{const url=new URL('https://qyapi.weixin.qq.com/cgi-bin/message/send');url.searchParams.set('access_token',access);const r=await transport(url,{method:'POST',redirect:'error',signal:AbortSignal.timeout(5000),headers:{'content-type':'application/json'},body:JSON.stringify({touser:toUser,msgtype:'text',agentid:Number(config.agentId),text:{content},safe:0})});const data=await r.json() as any;if(!r.ok||typeof data.errcode!=='number')return {status:'unknown'};if(data.errcode!==0||data.invaliduser||data.unlicenseduser)return {status:'failed',code:'WECOM_REJECTED'};return {status:'sent',messageId:typeof data.msgid==='string'?data.msgid:undefined};}catch{return {status:'unknown'};}
 }};
}

