import {resolveMember,listMembers} from './members.ts';
import {randomUUID,createHash} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import type {Principal} from '../../packages/platform-contracts/index.ts';
export type ExceptionStatus='open'|'in_progress'|'resolved'|'closed';
export interface ExceptionRecord {id:string;tenant:string;objectId:string;sourceVersion:number;issueKey:string;owner:string;summary:string;status:ExceptionStatus;sourceClear:boolean;version:number;audit:Array<{event:string;actor:string;note:string;at:string;version:number;from?:ExceptionStatus;to?:ExceptionStatus;owner?:string}>}
export interface ExceptionObject {id:string;version:number;observedAt?:string;issues:Array<{key:string;owner:string;summary:string}>}
export interface ExceptionTransition {expectedVersion:number;status?:ExceptionStatus;owner?:string;note:string}
const actorId=(v:unknown)=>typeof v==='string'&&/^[\w-]{1,60}$/.test(v);
const validText=(v:unknown,max:number)=>typeof v==='string'&&v.trim().length>0&&v.length<=max;
const errors=new Set(['VALIDATION_ERROR','FORBIDDEN','NOT_FOUND','VERSION_CONFLICT','IDEMPOTENCY_CONFLICT','INVALID_TRANSITION','SOURCE_NOT_CLEAR']);
async function transaction<T>(db:Pool,tenant:string,fn:(c:PoolClient)=>Promise<T>):Promise<T>{const c=await db.connect();try{await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,0))',['exceptions:'+tenant]);const result=await fn(c);await c.query('COMMIT');return result;}catch(error){await c.query('ROLLBACK');if(error instanceof Error&&errors.has(error.message))throw error;throw new Error('SERVICE_UNAVAILABLE');}finally{c.release();}}
function identity(p:Principal){if(!p||!validText(p.tenant,60)||!actorId(p.actor))throw new Error('FORBIDDEN');}
function audit(e:ExceptionRecord,event:string,actor:string,note:string,from?:ExceptionStatus){e.audit.push({event,actor,note,at:new Date().toISOString(),version:e.version,...(from?{from,to:e.status}:{}),owner:e.owner});}
async function save(c:PoolClient,e:ExceptionRecord){await c.query('INSERT INTO platform_exceptions(tenant,id,object_id,issue_key,data) VALUES($1,$2,$3,$4,$5) ON CONFLICT(tenant,id) DO UPDATE SET data=EXCLUDED.data',[e.tenant,e.id,e.objectId,e.issueKey,e]);}
export async function migrateExceptions(db:Pool){await db.query(`CREATE TABLE IF NOT EXISTS platform_exceptions(tenant text NOT NULL,id text NOT NULL,object_id text NOT NULL,issue_key text NOT NULL,data jsonb NOT NULL,PRIMARY KEY(tenant,id),UNIQUE(tenant,object_id,issue_key));CREATE TABLE IF NOT EXISTS exception_sources(tenant text NOT NULL,object_id text NOT NULL,version integer NOT NULL,PRIMARY KEY(tenant,object_id));ALTER TABLE exception_sources ADD COLUMN IF NOT EXISTS observed_at timestamptz NOT NULL DEFAULT '1970-01-01T00:00:00Z';CREATE TABLE IF NOT EXISTS exception_mutations(tenant text NOT NULL,key text NOT NULL,fingerprint text NOT NULL,result jsonb NOT NULL,PRIMARY KEY(tenant,key));`);}
export async function reconcileExceptions(db:Pool,tenant:string,objects:ExceptionObject[]):Promise<ExceptionRecord[]>{
 if(!validText(tenant,60)||!Array.isArray(objects)||objects.length>10000)throw new Error('VALIDATION_ERROR');
 const members=await listMembers(db,tenant);
 const ids=new Set<string>();for(const o of objects){if(!o||!validText(o.id,120)||!Number.isSafeInteger(o.version)||o.version<1||!Array.isArray(o.issues)||ids.has(o.id)||o.observedAt!==undefined&&(typeof o.observedAt!=='string'||!/^\d{4}-\d{2}-\d{2}T\d{2}:\d{2}:\d{2}(?:\.\d{1,3})?(?:Z|[+-]\d{2}:\d{2})$/.test(o.observedAt)||!Number.isFinite(Date.parse(o.observedAt))))throw new Error('VALIDATION_ERROR');ids.add(o.id);const keys=new Set<string>();for(const i of o.issues){if(!i||!validText(i.key,200)||!actorId(i.owner)||!members.some(m=>m.actor===i.owner)||!validText(i.summary,2000)||keys.has(i.key))throw new Error('VALIDATION_ERROR');keys.add(i.key);}}
 return transaction(db,tenant,async c=>{for(const o of objects){const observedAt=o.observedAt??'1970-01-01T00:00:00Z';const source=(await c.query('SELECT version,observed_at FROM exception_sources WHERE tenant=$1 AND object_id=$2',[tenant,o.id])).rows[0];const observation=Date.parse(observedAt);const priorObservation=source?new Date(source.observed_at).getTime():0;if(source&&(source.version>o.version||observation<priorObservation||source.version===o.version&&observation===priorObservation))continue;
 const existing:ExceptionRecord[]=(await c.query('SELECT data FROM platform_exceptions WHERE tenant=$1 AND object_id=$2',[tenant,o.id])).rows.map(r=>r.data);
 for(const issue of o.issues){let e=existing.find(e=>e.issueKey===issue.key);if(!e){e={id:randomUUID(),tenant,objectId:o.id,sourceVersion:o.version,issueKey:issue.key,owner:issue.owner,summary:issue.summary,status:'open',sourceClear:false,version:1,audit:[]};audit(e,'created','patrol','巡检发现异常');}else{const from=e.status;const reappeared=e.sourceClear;e.sourceVersion=o.version;e.summary=issue.summary;e.sourceClear=false;e.version++;if(e.status==='closed')e.status='open';audit(e,from==='closed'?'reopened':reappeared?'source_reappeared':'evidence_updated','patrol','巡检更新业务依据',from);}await save(c,e);}
 for(const e of existing.filter(e=>!o.issues.some(i=>i.key===e.issueKey)&&!e.sourceClear)){e.sourceClear=true;e.sourceVersion=o.version;e.version++;audit(e,'source_cleared','patrol','业务异常已消失，等待人工完成处理');await save(c,e);}
 await c.query('INSERT INTO exception_sources(tenant,object_id,version,observed_at) VALUES($1,$2,$3,$4) ON CONFLICT(tenant,object_id) DO UPDATE SET version=EXCLUDED.version,observed_at=EXCLUDED.observed_at',[tenant,o.id,o.version,observedAt]);}
 return (await c.query('SELECT data FROM platform_exceptions WHERE tenant=$1 ORDER BY object_id,issue_key',[tenant])).rows.map(r=>r.data);});
}
export async function listExceptions(db:Pool,principal:Principal):Promise<ExceptionRecord[]>{identity(principal);await resolveMember(db,principal);try{return (await db.query('SELECT data FROM platform_exceptions WHERE tenant=$1 ORDER BY object_id,issue_key',[principal.tenant])).rows.map(r=>r.data);}catch{throw new Error('SERVICE_UNAVAILABLE');}}
export async function transitionException(db:Pool,principal:Principal,id:string,input:ExceptionTransition,idempotencyKey:string):Promise<ExceptionRecord>{
 identity(principal);const member=await resolveMember(db,principal);if(input?.owner!==undefined)await resolveMember(db,{tenant:principal.tenant,actor:input.owner});if(!validText(id,120)||!validText(idempotencyKey,160)||!input||Object.keys(input).some(k=>!['expectedVersion','status','owner','note'].includes(k))||!Number.isSafeInteger(input.expectedVersion)||input.expectedVersion<1||!validText(input.note,1000)||input.status===undefined&&input.owner===undefined||input.status!==undefined&&!['open','in_progress','resolved','closed'].includes(input.status)||input.owner!==undefined&&!actorId(input.owner))throw new Error('VALIDATION_ERROR');
 const fingerprint=createHash('sha256').update(JSON.stringify({actor:principal.actor,id,expectedVersion:input.expectedVersion,status:input.status??null,owner:input.owner??null,note:input.note})).digest('hex');
 return transaction(db,principal.tenant,async c=>{const previous=(await c.query('SELECT * FROM exception_mutations WHERE tenant=$1 AND key=$2',[principal.tenant,idempotencyKey])).rows[0];if(previous){if(previous.fingerprint!==fingerprint)throw new Error('IDEMPOTENCY_CONFLICT');return previous.result;}
 const e:ExceptionRecord|undefined=(await c.query('SELECT data FROM platform_exceptions WHERE tenant=$1 AND id=$2',[principal.tenant,id])).rows[0]?.data;if(!e)throw new Error('NOT_FOUND');
 if(input.owner!==undefined&&member.role!=='manager'||member.role!=='manager'&&principal.actor!==e.owner||input.status==='closed'&&member.role!=='manager')throw new Error('FORBIDDEN');
 if(e.version!==input.expectedVersion)throw new Error('VERSION_CONFLICT');if(e.status==='closed')throw new Error('INVALID_TRANSITION');
 const allowed:Record<ExceptionStatus,ExceptionStatus[]>={open:['in_progress','resolved'],in_progress:['resolved'],resolved:['in_progress','closed'],closed:[]};if(input.status!==undefined&&!allowed[e.status].includes(input.status))throw new Error('INVALID_TRANSITION');if(input.status==='closed'&&!e.sourceClear)throw new Error('SOURCE_NOT_CLEAR');
 const from=e.status;if(input.owner!==undefined)e.owner=input.owner;if(input.status)e.status=input.status;e.version++;audit(e,input.status?'transitioned':'assigned',principal.actor,input.note,from);await save(c,e);await c.query('INSERT INTO exception_mutations VALUES($1,$2,$3,$4)',[principal.tenant,idempotencyKey,fingerprint,e]);return e;});
}

