import {createDecipheriv,createHash,timingSafeEqual} from 'node:crypto';
import type {FastifyInstance} from 'fastify';import type {Pool} from 'pg';import {receiveFeedback} from './channel.ts';
export interface WecomConfig {corpId:string;agentId:string;token:string;aesKey:string;secret:string;enabled:boolean}
export function readWecomConfig(env:NodeJS.ProcessEnv=process.env):WecomConfig|null {const values=[env.WECOM_CORP_ID,env.WECOM_AGENT_ID,env.WECOM_CALLBACK_TOKEN,env.WECOM_ENCODING_AES_KEY];if(values.every(v=>!v))return null;if(values.some(v=>!v)||!/^\d+$/.test(values[1]!)||!/^[A-Za-z0-9+/]{43}$/.test(values[3]!))throw new Error('CHANNEL_NOT_CONFIGURED');return {corpId:values[0]!,agentId:values[1]!,token:values[2]!,aesKey:values[3]!,secret:env.WECOM_APP_SECRET??'',enabled:env.WECOM_SEND_ENABLED==='true'};}
export function verifyWecomSignature(c:WecomConfig,timestamp:string,nonce:string,encrypted:string,signature:string,now=Date.now()) {if(!/^\d{10}$/.test(timestamp)||Math.abs(now-Number(timestamp)*1000)>300000||!nonce||nonce.length>256||encrypted.length>100000||!/^[a-fA-F0-9]{40}$/.test(signature))throw new Error('FORBIDDEN');const digest=createHash('sha1').update([c.token,timestamp,nonce,encrypted].sort().join('')).digest();if(!timingSafeEqual(digest,Buffer.from(signature,'hex')))throw new Error('FORBIDDEN');}
export function decryptWecom(c:WecomConfig,encrypted:string):string {try{if(!encrypted||encrypted.length>100000||!/^[A-Za-z0-9+/]+={0,2}$/.test(encrypted))throw 0;const key=Buffer.from(c.aesKey+'=','base64'),bytes=Buffer.from(encrypted,'base64');if(key.length!==32||bytes.length%16||bytes.toString('base64')!==encrypted)throw 0;const decipher=createDecipheriv('aes-256-cbc',key,key.subarray(0,16));decipher.setAutoPadding(false);const padded=Buffer.concat([decipher.update(bytes),decipher.final()]);const padding=padded[padded.length-1];if(padding<1||padding>32||!padded.subarray(-padding).every(b=>b===padding))throw 0;const raw=padded.subarray(0,-padding);if(raw.length<20)throw 0;const length=raw.readUInt32BE(16);if(length>65536||20+length>raw.length||!raw.subarray(20+length).equals(Buffer.from(c.corpId)))throw 0;return new TextDecoder('utf-8',{fatal:true}).decode(raw.subarray(20,20+length));}catch{throw new Error('FORBIDDEN');}}
// Deliberately bounded flat XML subset: no DTD, attributes, nested elements or external entities.
export function parseXml(xml:string):Record<string,string>{if(typeof xml!=='string'||Buffer.byteLength(xml)>100000||/[\u0000-\u0008\u000b\u000c\u000e-\u001f]/.test(xml))throw new Error('VALIDATION_ERROR');const root=/^\s*<xml>\s*([\s\S]*?)\s*<\/xml>\s*$/.exec(xml);if(!root)throw new Error('VALIDATION_ERROR');const out:Record<string,string>={};let rest=root[1],count=0;while(rest.trim()){const m=/^\s*<([A-Za-z][A-Za-z0-9_]{0,63})>(?:<!\[CDATA\[([\s\S]*?)\]\]>|([^<]*))<\/\1>/.exec(rest);if(!m||Object.hasOwn(out,m[1])||++count>32)throw new Error('VALIDATION_ERROR');const raw=m[2]??m[3];if(m[2]===undefined&&/&(?!(?:amp|lt|gt|quot|apos);)/.test(raw))throw new Error('VALIDATION_ERROR');Object.defineProperty(out,m[1],{value:m[2]??raw.replace(/&(amp|lt|gt|quot|apos);/g,(_,n:'amp'|'lt'|'gt'|'quot'|'apos')=>({amp:'&',lt:'<',gt:'>',quot:'"',apos:"'"}[n]!)),enumerable:true});rest=rest.slice(m[0].length);}return out;}
export function parseFeedbackCommand(content:string):Record<string,unknown>{const m=/^反馈 ([A-Za-z0-9_-]{1,100}) ([A-Za-z0-9_-]{1,100}) v([1-9]\d{0,8}) (?:数量(\d{1,9})\/(\d{1,9})|百分比(\d{1,3})%)(?: 预计(\d{4}-\d{2}-\d{2}))?$/.exec(content);if(!m)throw new Error('VALIDATION_ERROR');const out:Record<string,unknown>={orderId:m[1],nodeId:m[2],expectedVersion:Number(m[3]),mode:m[6]===undefined?'quantity':'percent'};if(m[6]!==undefined){if(Number(m[6])>100)throw new Error('VALIDATION_ERROR');out.percent=Number(m[6]);}else{if(Number(m[5])<=0||Number(m[4])>Number(m[5]))throw new Error('VALIDATION_ERROR');out.completed=Number(m[4]);out.total=Number(m[5]);}if(m[7]){const d=new Date(m[7]+'T00:00:00Z');if(!Number.isFinite(d.getTime())||d.toISOString().slice(0,10)!==m[7])throw new Error('VALIDATION_ERROR');out.expectedFinish=m[7];}return out;}
export async function receiveWecom(db:Pool,c:WecomConfig,xml:string,invoke:Parameters<typeof receiveFeedback>[2]) {const m=parseXml(xml);if(m.ToUserName!==c.corpId||m.AgentID!==c.agentId||!m.FromUserName||m.FromUserName.length>100)throw new Error('FORBIDDEN');if(!/^\d{1,30}$/.test(m.MsgId??''))throw new Error('VALIDATION_ERROR');if(m.MsgType!=='text')throw new Error('WECOM_ASSOCIATION_REQUIRED');return receiveFeedback(db,{channel:'wecom',eventId:m.MsgId,senderId:m.FromUserName,...parseFeedbackCommand(m.Content??'')},invoke);}
export function installWecom(app:FastifyInstance,db:Pool,invoke:Parameters<typeof receiveFeedback>[2],config:WecomConfig|null=readWecomConfig()) {app.register(async scope=>{scope.addContentTypeParser(['application/xml','text/xml'],{parseAs:'string',bodyLimit:100000},(_req,body,done)=>done(null,body));
 const decode=(query:any,encrypted:string)=>{if(!config)throw new Error('CHANNEL_NOT_CONFIGURED');verifyWecomSignature(config,query.timestamp,query.nonce,encrypted,query.msg_signature);return decryptWecom(config,encrypted);};
 scope.get('/api/wecom/callback',async(req,reply)=>{try{const q=req.query as any;const plain=decode(q,q.echostr);return reply.type('text/plain').send(plain);}catch{return reply.code(config?403:503).send('unavailable');}});
 scope.post('/api/wecom/callback',{bodyLimit:100000},async(req,reply)=>{try{const outer=parseXml(req.body as string);const xml=decode(req.query,outer.Encrypt);await receiveWecom(db,config!,xml,invoke);return reply.type('text/plain').send('success');}catch(error){const code=(error as Error).message;const status=code==='CHANNEL_DELIVERY_UNKNOWN'?503:code==='CHANNEL_NOT_CONFIGURED'?503:code==='FORBIDDEN'?403:400;return reply.code(status).send({code:['WECOM_ASSOCIATION_REQUIRED','VALIDATION_ERROR','FORBIDDEN','VERSION_CONFLICT','IDEMPOTENCY_CONFLICT','CHANNEL_DELIVERY_UNKNOWN'].includes(code)?code:'WECOM_CALLBACK_REJECTED'});}});
 });}

