import {assertManager,assertIdentity,activeOwner,isManager} from '../../packages/member-authorization/index.ts';
import {createHash,randomUUID} from 'node:crypto';
import type {Pool,PoolClient} from 'pg';
import type {Order} from '../../packages/sampling-contracts/index.ts';
import {validDate} from './project.ts';
export interface ChangePrincipal {tenant:string;actor:string}
export interface ChangeInput {orderId:string;sourceVersion:number;due:string;extraCostCents:number;reason:string}
export interface ChangePlan extends ChangeInput {id:string;tenant:string;proposedBy:string;planVersion:number;status:'proposed'|'approved'|'rejected'|'applied';decidedBy:string|null;createdAt:string}
export interface ChangeInvocation {id:string;changeId:string;status:'completed';result:Order}
const codes=new Set(['VALIDATION_ERROR','FORBIDDEN','NOT_FOUND','VERSION_CONFLICT','IDEMPOTENCY_CONFLICT','CHANGE_NOT_APPROVED','CHANGE_ALREADY_APPLIED','CHANGE_ALREADY_DECIDED']);
function safe(error:unknown):Error{return error instanceof Error&&codes.has(error.message)?error:new Error('SERVICE_UNAVAILABLE');}
function principal(p:ChangePrincipal,manager=false){assertIdentity(p);if(!p||typeof p.tenant!=='string'||!p.tenant.trim()||p.tenant.length>100||!activeOwner(p.actor)||manager&&!isManager(p.actor))throw new Error('FORBIDDEN');}
function identifier(id:unknown):asserts id is string {if(typeof id!=='string'||!id.trim()||id.length>100)throw new Error('VALIDATION_ERROR');}
export function validateChangeInput(raw:unknown):ChangeInput {
 if(!raw||typeof raw!=='object'||Array.isArray(raw))throw new Error('VALIDATION_ERROR');
 const input=raw as ChangeInput;const fields=['orderId','sourceVersion','due','extraCostCents','reason'];
 if(Object.keys(raw).some(k=>!fields.includes(k))||!Number.isSafeInteger(input.sourceVersion)||input.sourceVersion<1||!validDate(input.due)||!Number.isSafeInteger(input.extraCostCents)||input.extraCostCents<0||typeof input.reason!=='string'||!input.reason.trim()||input.reason.length>500)throw new Error('VALIDATION_ERROR');
 identifier(input.orderId);return {orderId:input.orderId,sourceVersion:input.sourceVersion,due:input.due,extraCostCents:input.extraCostCents,reason:input.reason};
}
export async function migrateChanges(db:Pool){await db.query(`CREATE TABLE IF NOT EXISTS change_plans(id text PRIMARY KEY,tenant text NOT NULL,order_id text NOT NULL,source_version integer NOT NULL,due text NOT NULL,extra_cost_cents bigint NOT NULL,reason text NOT NULL,proposed_by text NOT NULL,plan_version integer NOT NULL DEFAULT 1,status text NOT NULL DEFAULT 'proposed',decided_by text,created_at timestamptz NOT NULL DEFAULT now());
 CREATE TABLE IF NOT EXISTS change_invocations(id text PRIMARY KEY,tenant text NOT NULL,change_id text NOT NULL UNIQUE,key text NOT NULL,result jsonb NOT NULL,UNIQUE(tenant,key));
 CREATE OR REPLACE FUNCTION guard_change_content() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF TG_OP='DELETE' THEN RAISE EXCEPTION 'change plan immutable'; END IF;
 IF ROW(NEW.id,NEW.tenant,NEW.order_id,NEW.source_version,NEW.due,NEW.extra_cost_cents,NEW.reason,NEW.proposed_by,NEW.plan_version,NEW.created_at) IS DISTINCT FROM ROW(OLD.id,OLD.tenant,OLD.order_id,OLD.source_version,OLD.due,OLD.extra_cost_cents,OLD.reason,OLD.proposed_by,OLD.plan_version,OLD.created_at) THEN RAISE EXCEPTION 'change plan immutable'; END IF;
 RETURN NEW; END; $$;
 DROP TRIGGER IF EXISTS guard_change_content ON change_plans;CREATE TRIGGER guard_change_content BEFORE UPDATE OR DELETE ON change_plans FOR EACH ROW EXECUTE FUNCTION guard_change_content();
 CREATE OR REPLACE FUNCTION guard_change_invocation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RAISE EXCEPTION 'change invocation immutable'; END; $$;
 DROP TRIGGER IF EXISTS guard_change_invocation ON change_invocations;CREATE TRIGGER guard_change_invocation BEFORE UPDATE OR DELETE ON change_invocations FOR EACH ROW EXECUTE FUNCTION guard_change_invocation();`);}
function plan(row:any):ChangePlan{return {id:row.id,tenant:row.tenant,orderId:row.order_id,sourceVersion:row.source_version,due:row.due,extraCostCents:Number(row.extra_cost_cents),reason:row.reason,proposedBy:row.proposed_by,planVersion:row.plan_version,status:row.status,decidedBy:row.decided_by,createdAt:new Date(row.created_at).toISOString()};}
async function tx<T>(db:Pool,p:ChangePrincipal,body:(c:PoolClient)=>Promise<T>):Promise<T>{let c:PoolClient|undefined;try{c=await db.connect();await c.query('BEGIN');await c.query('SELECT pg_advisory_xact_lock(hashtextextended($1,1))',[p.tenant]);const result=await body(c);await c.query('COMMIT');return result;}catch(e){if(c)await c.query('ROLLBACK').catch(()=>{});throw safe(e);}finally{c?.release();}}
async function load(c:Pool|PoolClient,p:ChangePrincipal,id:string){const row=(await c.query('SELECT * FROM change_plans WHERE tenant=$1 AND id=$2',[p.tenant,id])).rows[0];if(!row)throw new Error('NOT_FOUND');return plan(row);}
async function source(c:PoolClient,p:ChangePrincipal,change:ChangeInput):Promise<Order>{const row=(await c.query('SELECT data FROM orders WHERE tenant=$1 AND id=$2 FOR UPDATE',[p.tenant,change.orderId])).rows[0];if(!row)throw new Error('NOT_FOUND');if(row.data.version!==change.sourceVersion)throw new Error('VERSION_CONFLICT');return row.data;}
const fingerprint=(body:unknown)=>createHash('sha256').update(JSON.stringify(body)).digest('hex');
async function replay(c:PoolClient,p:ChangePrincipal,key:string,hash:string){const row=(await c.query('SELECT * FROM mutations WHERE tenant=$1 AND key=$2',[p.tenant,key])).rows[0];if(row&&row.fingerprint!==hash)throw new Error('IDEMPOTENCY_CONFLICT');return row?.result;}
async function remember(c:PoolClient,p:ChangePrincipal,key:string,hash:string,result:unknown){await c.query('INSERT INTO mutations VALUES($1,$2,$3,$4)',[p.tenant,key,hash,JSON.stringify(result)]);}
export async function proposeChange(db:Pool,p:ChangePrincipal,raw:unknown,key:string):Promise<ChangePlan>{principal(p,true);identifier(key);const input=validateChangeInput(raw);const hash=fingerprint({kind:'propose-change',actor:p.actor,input});return tx(db,p,async c=>{const old=await replay(c,p,key,hash);if(old)return old;await source(c,p,input);const row=(await c.query('INSERT INTO change_plans(id,tenant,order_id,source_version,due,extra_cost_cents,reason,proposed_by) VALUES($1,$2,$3,$4,$5,$6,$7,$8) RETURNING *',[randomUUID(),p.tenant,input.orderId,input.sourceVersion,input.due,input.extraCostCents,input.reason,p.actor])).rows[0];const result=plan(row);await remember(c,p,key,hash,result);return result;});}
export async function decideChange(db:Pool,p:ChangePrincipal,id:string,decision:'approve'|'reject',expectedPlanVersion:number):Promise<ChangePlan>{principal(p,true);identifier(id);if(!['approve','reject'].includes(decision)||!Number.isSafeInteger(expectedPlanVersion)||expectedPlanVersion<1)throw new Error('VALIDATION_ERROR');return tx(db,p,async c=>{const change=await load(c,p,id);if(change.planVersion!==expectedPlanVersion)throw new Error('VERSION_CONFLICT');await source(c,p,change);if(change.status!=='proposed')throw new Error('CHANGE_ALREADY_DECIDED');return plan((await c.query('UPDATE change_plans SET status=$3,decided_by=$4 WHERE tenant=$1 AND id=$2 RETURNING *',[p.tenant,id,decision==='approve'?'approved':'rejected',p.actor])).rows[0]);});}
export async function applyChange(db:Pool,p:ChangePrincipal,id:string,key:string):Promise<ChangeInvocation>{principal(p,true);identifier(id);identifier(key);const hash=fingerprint({kind:'apply-change',actor:p.actor,id});return tx(db,p,async c=>{const old=await replay(c,p,key,hash);if(old)return old;const change=await load(c,p,id);if(change.status==='applied')throw new Error('CHANGE_ALREADY_APPLIED');if(change.status!=='approved')throw new Error('CHANGE_NOT_APPROVED');const order=await source(c,p,change);const updated={...order,due:change.due,version:order.version+1,approvedChanges:[...((order as any).approvedChanges??[]),{changeId:change.id,extraCostCents:change.extraCostCents,reason:change.reason,approvedBy:change.decidedBy,sourceVersion:change.sourceVersion}]};const result:ChangeInvocation={id:randomUUID(),changeId:id,status:'completed',result:updated};await c.query('UPDATE orders SET data=$3 WHERE tenant=$1 AND id=$2',[p.tenant,order.id,JSON.stringify(updated)]);await c.query("UPDATE change_plans SET status='applied' WHERE tenant=$1 AND id=$2",[p.tenant,id]);await c.query('INSERT INTO change_invocations VALUES($1,$2,$3,$4,$5)',[result.id,p.tenant,id,key,JSON.stringify(result)]);await c.query('INSERT INTO outbox(id,tenant,object_id,version) VALUES($1,$2,$3,$4)',[randomUUID(),p.tenant,order.id,updated.version]);await remember(c,p,key,hash,result);return result;});}
export async function getChange(db:Pool,p:ChangePrincipal,id:string):Promise<ChangePlan>{principal(p);identifier(id);try{return await load(db,p,id);}catch(e){throw safe(e);}}
export async function listChanges(db:Pool,p:ChangePrincipal):Promise<ChangePlan[]>{principal(p);try{return (await db.query('SELECT * FROM change_plans WHERE tenant=$1 ORDER BY created_at DESC,id',[p.tenant])).rows.map(plan);}catch(e){throw safe(e);}}
export async function getInvocation(db:Pool,p:ChangePrincipal,lookup:{id:string}|{key:string}):Promise<ChangeInvocation>{principal(p);if(!lookup||typeof lookup!=='object'||Object.keys(lookup).length!==1)throw new Error('VALIDATION_ERROR');const byId='id' in lookup;if(!byId&&!('key' in lookup))throw new Error('VALIDATION_ERROR');const value=byId?lookup.id:(lookup as {key:string}).key;identifier(value);try{const row=(await db.query(`SELECT result FROM change_invocations WHERE tenant=$1 AND ${byId?'id':'key'}=$2`,[p.tenant,value])).rows[0];if(!row)throw new Error('NOT_FOUND');return row.result;}catch(e){throw safe(e);}}
