import {chromium} from 'playwright-core';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const base='http://127.0.0.1:5179';const stamp=Date.now();const id='UI-'+stamp;const errors=[];await mkdir('.runtime/browser',{recursive:true});
async function api(path,body,key=crypto.randomUUID()){const response=await fetch(base+path,{method:body===undefined?'GET':'POST',headers:{'x-demo-user':'chen','content-type':'application/json','idempotency-key':key},body:body===undefined?undefined:JSON.stringify(body)});if(!response.ok)throw Error(path+':'+response.status+':'+await response.text());return response.json();}
assert.equal((await api('/api/runtime')).enabled,false,'Browser acceptance requires model dispatch disabled');
const project={id,product:'浏览器验收音箱',customer:'本地测试',due:'2026-10-09',calendar:{weekdays:[1,2,3,4,5],holidays:[]},nodes:[{id:'sample',name:'样机验证',owner:'chen',due:'2026-10-08',weight:1,durationDays:1,dependencies:[],acceptanceCriteria:'数量及检测记录核对'}]};
async function chooseMode(page,dialog,label,field){for(let i=0;i<3;i++){await dialog.getByRole('combobox').first().click();await page.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden) .ant-select-item-option-content').filter({hasText:label}).click();try{await dialog.getByLabel(field,{exact:true}).waitFor({state:'visible',timeout:2000});return;}catch{await page.keyboard.press('Escape');}}throw Error('Mode selection failed: '+label);}
const browser=await chromium.launch({channel:process.env.SOUNDLAB_BROWSER_CHANNEL??'chrome',headless:true});let template;
try{
 const page=await browser.newPage({viewport:{width:1440,height:1000}});page.setDefaultTimeout(10000);page.on('pageerror',e=>errors.push(e.message));await page.goto(base);await page.getByRole('button',{name:'新建 / 导入项目',exact:true}).click();let dialog=page.getByRole('dialog');
 await chooseMode(page,dialog,'导入单个项目 JSON','项目 JSON');await dialog.getByLabel('项目 JSON',{exact:true}).fill(JSON.stringify(project));await dialog.getByLabel('模板名称',{exact:true}).fill('验收模板-'+stamp);
 let response=page.waitForResponse(r=>r.url().endsWith('/api/soundlab/templates')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'保存为新模板',exact:true}).click();template=await(await response).json();assert.ok(template.id);await dialog.getByRole('button',{name:'更新当前模板',exact:true}).waitFor();
 await chooseMode(page,dialog,'批量导入 JSON（最多 50 个）','批量项目 JSON');await dialog.getByLabel('批量项目 JSON',{exact:true}).fill(JSON.stringify([project,{...project,id:id+'-B'}]));await dialog.getByRole('button',{name:'预览并校验'}).click();await dialog.getByText('项目配置校验通过；提交时将检查已有单号。',{exact:true}).waitFor();
 response=page.waitForResponse(r=>r.url().endsWith('/api/soundlab/orders/batch')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'确认整批导入'}).click();assert.equal((await response).status(),200);await dialog.waitFor({state:'hidden'});
 await page.getByRole('textbox',{name:'搜索订单'}).fill(id);await page.getByRole('cell',{name:id,exact:false}).first().click();await page.screenshot({path:'.runtime/browser/desktop.png',fullPage:true,animations:'disabled'});
 await page.getByRole('button',{name:'运行设置与平台管理',exact:true}).click();dialog=page.getByRole('dialog');await dialog.getByText('场景与业务连接',{exact:true}).waitFor();assert.equal(await dialog.getByRole('button',{name:'保存场景绑定'}).count(),1);await page.keyboard.press('Escape');await dialog.waitFor({state:'hidden'});
 const mobile=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});mobile.on('pageerror',e=>errors.push(e.message));await mobile.goto(base+'/mobile');await mobile.getByRole('combobox',{name:'演示身份'}).click();await mobile.locator('.ant-select-dropdown:not(.ant-select-dropdown-hidden) .ant-select-item-option-content').filter({hasText:'陈静'}).click();await mobile.getByRole('combobox',{name:'选择打样订单'}).fill(id);await mobile.getByText(id+' · 浏览器验收音箱',{exact:true}).click();await mobile.getByRole('button',{name:'提交节点反馈',exact:true}).click();dialog=mobile.getByRole('dialog');await dialog.getByLabel('已完成数量',{exact:true}).fill('2');await dialog.getByLabel('目标数量',{exact:true}).fill('2');await mobile.screenshot({path:'.runtime/browser/mobile.png',fullPage:true,animations:'disabled'});
 response=mobile.waitForResponse(r=>r.url().endsWith('/'+id+'/feedback')&&r.request().method()==='POST');await dialog.getByRole('button',{name:'保存进度反馈'}).click();assert.equal((await response).status(),200);await dialog.waitFor({state:'hidden'});
 let order=(await api('/api/soundlab/orders')).find(o=>o.id===id);assert.equal(order.nodes[0].status,'reported_complete');await api('/api/soundlab/orders/'+id+'/accept',{nodeId:'sample',expectedVersion:order.version,note:'浏览器反馈验收通过'});
 order=await api('/api/soundlab/orders/'+id+'-B/feedback',{nodeId:'sample',expectedVersion:1,completed:1,total:1});await api('/api/soundlab/orders/'+id+'-B/accept',{nodeId:'sample',expectedVersion:order.version,note:'批量导入验收通过'});
 assert.deepEqual(errors,[]);const result={checkedAt:new Date().toISOString(),ids:[id,id+'-B'],template:true,batchUI:true,mobileFeedbackUI:true,desktopWidth:1440,mobileWidth:390,pageErrors:errors,modelRequestSent:false};await writeFile('.runtime/browser/acceptance.json',JSON.stringify(result,null,2));console.log(JSON.stringify(result));
}catch(error){console.error(error);throw error;}finally{if(template?.id)await api('/api/soundlab/templates/'+template.id+'/delete',{expectedVersion:template.version}).catch(()=>{});await browser.close();}
