import {chromium} from 'playwright-core';import {mkdir,writeFile} from 'node:fs/promises';import assert from 'node:assert/strict';
const browser=await chromium.launch({channel:'chrome',headless:true});await mkdir('.runtime/layout',{recursive:true});const results=[];
try{for(const viewport of [{width:1366,height:768},{width:1536,height:1024}]){
 const page=await browser.newPage({viewport});const errors=[];page.on('pageerror',e=>errors.push(e.message));await page.route('**/api/chat',route=>route.fulfill({json:{enabled:false,messages:[]}}));await page.goto('http://127.0.0.1:5179');await page.locator('.detail .ant-table-tbody tr').first().waitFor();
 const dimensions=await page.evaluate(()=>{const shape=s=>{const e=document.querySelector(s),r=e.getBoundingClientRect();return {top:r.top,bottom:r.bottom,height:r.height,scroll:e.scrollHeight,client:e.clientHeight}};return {height:innerHeight,width:innerWidth,bodyHeight:document.documentElement.scrollHeight,bodyWidth:document.documentElement.scrollWidth,detail:shape('.detail'),nodes:shape('.detail>.ant-table-wrapper'),composer:shape('.agent-composer'),rows:[...document.querySelectorAll('.detail .ant-table-tbody tr')].map(r=>r.getBoundingClientRect().bottom)}});
 await page.screenshot({path:`.runtime/layout/desktop-${viewport.width}.png`,fullPage:true,animations:'disabled'});console.log(JSON.stringify(dimensions));assert.ok(dimensions.bodyHeight<=viewport.height+1);assert.ok(dimensions.bodyWidth<=viewport.width+1);assert.ok(dimensions.composer.bottom<=viewport.height);assert.equal(dimensions.rows.length,7);assert.ok(dimensions.nodes.scroll<=dimensions.nodes.client+1,'All seven nodes should fit without inner scrolling');
 await page.getByRole('textbox',{name:'声研助理输入'}).fill('查看 A26-021');await page.getByRole('button',{name:'发送助理指令'}).click();await page.locator('.detail-header').getByText('A26-021',{exact:false}).waitFor();assert.equal(await page.getByRole('textbox',{name:'搜索订单'}).inputValue(),'A26-021');await page.getByRole('button',{name:'交期依据与验收记录',exact:true}).click();await page.getByRole('dialog').getByRole('heading',{name:'原始反馈'}).waitFor();await page.keyboard.press('Escape');await page.getByRole('button',{name:'查看分析与证据',exact:true}).click();await page.getByRole('dialog').waitFor();await page.keyboard.press('Escape');assert.deepEqual(errors,[]);results.push({...viewport,dimensions,command:true,evidence:true,pageErrors:errors});await page.close();
 }
 const page=await browser.newPage({viewport:{width:390,height:844},isMobile:true,hasTouch:true});await page.goto('http://127.0.0.1:5179/mobile');await page.getByRole('combobox',{name:'选择打样订单'}).waitFor();await page.screenshot({path:'.runtime/layout/mobile.png',fullPage:true,animations:'disabled'});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth));results.push({mobile:true,width:390});await writeFile('.runtime/layout/verification.json',JSON.stringify(results,null,2));console.log('Layout and interaction verification passed');
}finally{await browser.close();}
