import {readdir,readFile,writeFile,mkdir,copyFile} from 'node:fs/promises';import {resolve,join,relative,sep} from 'node:path';import {createHash} from 'node:crypto';import {execFile} from 'node:child_process';import {promisify} from 'node:util';
const root=resolve('.');const stamp=new Date().toISOString().replaceAll(':','-');const output=resolve('.runtime/releases',stamp);const stage=join(output,'soundlab');await mkdir(stage,{recursive:true});
const entries=['apps','packages','scripts','migrations','config','docs','tests','dist/web','.github/workflows','README.md','.env.example','package.json','pnpm-lock.yaml','pnpm-workspace.yaml','tsconfig.json','docker-compose.yml'];
const files=[];const forbidden=name=>['node_modules','.git','.runtime','.codex','.agents'].includes(name)||(name.startsWith('.env')&&name!=='.env.example')||/\.(pem|key|pfx)$/i.test(name);
async function collect(path){const info=await import('node:fs/promises').then(fs=>fs.lstat(path));if(info.isSymbolicLink())return;if(info.isDirectory()){for(const entry of await readdir(path,{withFileTypes:true}))if(!forbidden(entry.name))await collect(join(path,entry.name));}else if(info.isFile())files.push(path);}
for(const entry of entries)await collect(resolve(root,entry));
const manifest=[];for(const file of files.sort()){const name=relative(root,file);if(name.startsWith('..'+sep)||name==='..')throw Error('OUTSIDE_RELEASE_ROOT');const target=join(stage,name);await mkdir(resolve(target,'..'),{recursive:true});await copyFile(file,target);const bytes=await readFile(target);manifest.push({path:name.replaceAll('\\','/'),bytes:bytes.length,sha256:createHash('sha256').update(bytes).digest('hex')});}
await writeFile(join(stage,'RELEASE-MANIFEST.json'),JSON.stringify({createdAt:new Date().toISOString(),harnessCommit:'d347e703908d0406b7a7ef80e3a0e594d86b2215',dependenciesIncluded:false,files:manifest},null,2));
const archive=join(output,'soundlab.tar.gz');await promisify(execFile)('tar',['-czf',archive,'-C',output,'soundlab'],{windowsHide:true});console.log(JSON.stringify({archive,files:manifest.length,sha256:createHash('sha256').update(await readFile(archive)).digest('hex'),secretsIncluded:false}));
